version: "3.2"
services:
  php:
    image: php
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  apache:
    image: httpd
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/html/
  mysql:
    image: mysql
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  frontend:
  backend: